"""Shared utility functions."""

from .aws_profile import (
    configure_aws_profile,
    configure_aws_profile_for_environment,
)
from .cli import (
    EnvironmentConfigError,
    EnvironmentInfrastructure,
    configure_aws_for_operation,
    configure_profile_or_exit,
    confirm_action,
    exit_on,
    iter_deployed_environments,
    load_environment_infrastructure,
    prompt_or_exit,
    require_environment,
    require_validated_environment,
    resolve_deploy_toml_or_exit,
    validate_and_configure,
)
from .colors import Colors
from .constants import AWS_REGION
from .datetime import format_iso, format_timestamp
from .environment import (
    ensure_environments_symlinks,
    get_all_environments,
    get_deployer_root,
    get_environment_path,
    get_environments_dir,
    validate_environment_deployed,
)
from .links import (
    get_all_links,
    get_linked_deploy_toml,
    get_links_file,
    set_linked_deploy_toml,
    unlink_deploy_toml,
)
from .logging import (
    advice_block,
    is_verbose,
    log,
    log_debug,
    log_error,
    log_error_stderr,
    log_info,
    log_ok,
    log_section,
    log_status,
    log_success,
    log_warning,
    log_warning_stderr,
    print_with_advice,
    set_verbose,
)
from .subprocess import run_command

__all__ = [
    "AWS_REGION",
    "Colors",
    "EnvironmentConfigError",
    "EnvironmentInfrastructure",
    "advice_block",
    "configure_aws_for_operation",
    "configure_aws_profile",
    "format_iso",
    "format_timestamp",
    "configure_aws_profile_for_environment",
    "configure_profile_or_exit",
    "confirm_action",
    "ensure_environments_symlinks",
    "exit_on",
    "get_all_environments",
    "get_all_links",
    "get_deployer_root",
    "get_environment_path",
    "get_environments_dir",
    "get_linked_deploy_toml",
    "get_links_file",
    "is_verbose",
    "iter_deployed_environments",
    "load_environment_infrastructure",
    "log",
    "log_debug",
    "log_error",
    "log_error_stderr",
    "log_info",
    "log_ok",
    "log_section",
    "log_status",
    "log_success",
    "log_warning",
    "log_warning_stderr",
    "print_with_advice",
    "prompt_or_exit",
    "require_environment",
    "require_validated_environment",
    "resolve_deploy_toml_or_exit",
    "run_command",
    "set_linked_deploy_toml",
    "set_verbose",
    "unlink_deploy_toml",
    "validate_and_configure",
    "validate_environment_deployed",
]
